name: Auto Update Sound Library

on:
  workflow_dispatch:
  push:
    paths:
      - addSounds.js

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios

      - name: Run sound updater
        run: node addSounds.js

      - name: Commit changes
        run: |
          git config user.name "sound-bot"
          git config user.email "sound-bot@users.noreply.github.com"
          git add sounds.json
          git commit -m "auto-update sounds.json" || echo "No changes"
          git push
